apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dagster-rds-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dagster-postgresql-secret
  data:
    - secretKey: password
      remoteRef:
        key: dagster-platform-rds-credentials
        property: password
    - secretKey: host
      remoteRef:
        key: dagster-platform-rds-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: dagster-platform-rds-credentials
        property: port
    - secretKey: username
      remoteRef:
        key: dagster-platform-rds-credentials
        property: username
    - secretKey: dbname
      remoteRef:
        key: dagster-platform-rds-credentials
        property: dbname
