apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_ORG/dagster-platform
    targetRevision: main
    path: platform/dagster/overlays/dev

  destination:
    name: dagster-dev
    namespace: dagster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: "*"
      kind: Secret
      jsonPointers:
        - /data
