apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: observability
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ADOT_COLLECTOR_ROLE_ARN
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot-collector
  namespace: observability
spec:
  # Use ADOT collector image which includes the awsxray exporter
  image: public.ecr.aws/aws-observability/aws-otel-collector:v0.46.0
  mode: daemonset
  serviceAccount: adot-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
      resource:
        attributes:
          - key: service.namespace
            action: insert
            value: dagster

    exporters:
      awsxray:
        region: REPLACE_AWS_REGION

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [awsxray]
